### ISSUE TITLE
In Moodle 5.0, get_bulk_actions() throws an error

### ISSUE THREAD

**Issue by lucaboesch** [bfh/moodle-qbank_bulkxmlexport#1]
On a test site, I noticed:

Fatal error: Declaration of qbank_bulkxmlexport\plugin_feature::get_bulk_actions(): array must be compatible with core_question\local\bank\plugin_features_base::get_bulk_actions(core_question\local\bank\view $qbank): array in /Users/luca/Documents/Dokumente - C2LQW26PC9/workspace.nosync/mdk/stable_master/moodle/question/bank/bulkxmlexport/classes/plugin_feature.php on line 34

**Comment by srobotta** [comment]
Fixed in current 5.0dev branch.
